[package]
name = "append-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.56"
log = "0.4.14"
thiserror = "1.0.31"
tokio = { version = "1", features = ["full"] }